---
deployment:
  tasks:
    - export DEPLOYPATH=/home/goleuwupz58z/public_html/v2/assets/plugin/
    - /bin/cp -R styles $DEPLOYPATH
    - export DEPLOYPATH=/home/goleuwupz58z/public_html/subdomain/project/
    - /bin/cp -R project $DEPLOYPATH
